language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os: linux
sudo: required

services:
  - postgresql

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

# command to install dependencies
install:
  - pip install -r devtest/requirements.txt
  - whereis google-chrome-stable
  - whereis chromedriver

before_script:
  - chmod +x devtest/test.sh
  - psql -c 'CREATE DATABASE dev;' -U postgres
  - psql -c "CREATE USER dev WITH PASSWORD 'WFwt8UDpkfUpRsVS';" -U postgres

# command to run tests
script: ./devtest/test.sh
