language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os: linux
sudo: required

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r devtest/requirements.txt
  # - sudo apt-get install postgresql
  # postgres is already preinstalled on Travis

before_script:
  # - sudo service postgresql start
  - chmod +x devtest/test.sh
  - psql -c 'CREATE DATABASE dev;' -U postgres
  - psql -c "CREATE USER dev WITH PASSWORD 'WFwt8UDpkfUpRsVS';" -U postgres

# command to run tests
script: ./devtest/test.sh
