language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os: linux
sudo: required

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r devtest/requirements.txt
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo apt-get install chromium-chromedriver

before_script:
  # - sudo service postgresql start
  - chmod +x devtest/test.sh
  - psql -c 'CREATE DATABASE dev;' -U postgres
  - psql -c "CREATE USER dev WITH PASSWORD 'WFwt8UDpkfUpRsVS';" -U postgres

# command to run tests
script: ./devtest/test.sh
