language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os: linux
sudo: required

# command to install dependencies
install:
  - sudo apt-get install postgresql
  - pip install -r devtest/requirements.txt

before_script:
  - sudo service postgresql start
  - chmod +x devtest/test.sh

# command to run tests
script: ./devtest/test.sh