language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os: linux
# sudo: required

# command to install dependencies
install:
  - pip install -r devtest/requirements.txt

# command to run tests
script: nose2 -v